# 1. Kubernetes secret holding the client credentials
apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
  namespace: demo-k8s-practice
type: Opaque
stringData:
  clientId: 60f5b022-fe88-4fad-9a4d-7a990204177a
  clientSecret: e8cdc90b444c174e0d75b5fa1b32659d3924503d9f6ad3076d765dd11f583db5
---
# 2. Connection to the Infisical instance
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalConnection
metadata:
  name: my-infisical-connection
  namespace: demo-k8s-practice
spec:
  address: https://eu.infisical.com
---
# 3. Auth using Universal Auth credentials
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: my-infisical-auth
  namespace: demo-k8s-practice
spec:
  infisicalConnectionRef:
    name: my-infisical-connection
    namespace: demo-k8s-practice
  method: universal
  universal:
    clientIdRef:
      name: universal-auth-credentials
      namespace: demo-k8s-practice
      key: clientId
    clientSecretRef:
      name: universal-auth-credentials
      namespace: demo-k8s-practice
      key: clientSecret
---
# 4. Sync secrets into a native Kubernetes Secret
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: my-static-secret
  namespace: demo-k8s-practice
spec:
  infisicalAuthRef:
    name: my-infisical-auth
    namespace: demo-k8s-practice
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectId: c9376968-4c55-4865-a829-0c685a87fd5d
      environmentSlug: dev
      secretPath: /
  targets:
    - name: managed-secret
      namespace: demo-k8s-practice
      kind: Secret
      creationPolicy: Owner