apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: postgres-infisical-secret
  namespace: demo-k8s-practice
spec:
  infisicalAuthRef:
    name: my-infisical-auth
    namespace: demo-k8s-practice
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectId: c9376968-4c55-4865-a829-0c685a87fd5d
      environmentSlug: dev
      secretPath: /
  targets:
    - name: postgres-secret
      namespace: demo-k8s-practice
      kind: Secret
      creationPolicy: Owner